### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'lower' after upgrade to v1.0.1

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-client#20]
After upgrade to v1.0.1 any command finishing with an error:
```
# linstor c lp
Traceback (most recent call last):
  File "/usr/bin/linstor", line 24, in <module>
    linstor_client_main.main()
  File "/usr/lib/python2.7/dist-packages/linstor_client_main.py", line 662, in main
    LinStorCLI().run()
  File "/usr/lib/python2.7/dist-packages/linstor_client_main.py", line 627, in run
    rc = self.parse_and_execute(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/linstor_client_main.py", line 342, in parse_and_execute
    rc = args.func(args)
  File "/usr/lib/python2.7/dist-packages/linstor_client/commands/controller_cmds.py", line 77, in cmd_print_controller_props
    return self.output_props_list(args, lstmsg, self._props_list)
  File "/usr/lib/python2.7/dist-packages/linstor_client/commands/commands.py", line 319, in output_props_list
    Commands._print_props(result, args)
  File "/usr/lib/python2.7/dist-packages/linstor_client/commands/commands.py", line 421, in _print_props
    tbl.show()
  File "/usr/lib/python2.7/dist-packages/linstor_client/table.py", line 376, in show
    if len(locales) > 1 and locales[1].lower() == 'utf-8':
AttributeError: 'NoneType' object has no attribute 'lower'
```

However with `--no-utf8`, it is working fine:
```
# linstor --no-utf8 c lp
+------------------------------------------------------------------+
| Key                                       | Value                |
|==================================================================|
| DrbdOptions/Net/after-sb-0pri             | discard-zero-changes |
| DrbdOptions/Net/after-sb-1pri             | discard-secondary    |
| DrbdOptions/Net/after-sb-2pri             | disconnect           |
| DrbdOptions/Net/max-buffers               | 36864                |
| DrbdOptions/Net/protocol                  | C                    |
| DrbdOptions/Net/rcvbuf-size               | 2097152              |
| DrbdOptions/Net/sndbuf-size               | 1048576              |
| DrbdOptions/PeerDevice/c-fill-target      | 10240                |
| DrbdOptions/PeerDevice/c-max-rate         | 737280               |
| DrbdOptions/PeerDevice/c-min-rate         | 20480                |
| DrbdOptions/PeerDevice/c-plan-ahead       | 10                   |
| defaultDebugSslConnector                  | DebugSslConnector    |
| defaultPlainConSvc                        | PlainConnector       |
| defaultSslConSvc                          |                      |
| netcom/DebugSslConnector/bindaddress      | ::0                  |
| netcom/DebugSslConnector/enabled          | true                 |
| netcom/DebugSslConnector/keyPasswd        | linstor              |
| netcom/DebugSslConnector/keyStore         | ssl/keystore.jks     |
| netcom/DebugSslConnector/keyStorePasswd   | linstor              |
| netcom/DebugSslConnector/port             | 3373                 |
| netcom/DebugSslConnector/sslProtocol      | TLSv1.2              |
| netcom/DebugSslConnector/trustStore       | ssl/certificates.jks |
| netcom/DebugSslConnector/trustStorePasswd | linstor              |
| netcom/DebugSslConnector/type             | ssl                  |
| netcom/PlainConnector/bindaddress         | 127.0.0.1            |
| netcom/PlainConnector/enabled             | true                 |
| netcom/PlainConnector/port                | 3376                 |
| netcom/PlainConnector/type                | plain                |
| netcom/SslConnector/bindaddress           | ::0                  |
| netcom/SslConnector/enabled               | true                 |
| netcom/SslConnector/keyPasswd             | linstor              |
| netcom/SslConnector/keyStore              | ssl/keystore.jks     |
| netcom/SslConnector/keyStorePasswd        | linstor              |
| netcom/SslConnector/port                  | 3377                 |
| netcom/SslConnector/sslProtocol           | TLSv1.2              |
| netcom/SslConnector/trustStore            | ssl/certificates.jks |
| netcom/SslConnector/trustStorePasswd      | linstor              |
| netcom/SslConnector/type                  | ssl                  |
+------------------------------------------------------------------+
```

```
# linstor --version
linstor 1.0.0; GIT-hash: d8c9a43d4eab20749132147ad61a2ee821645be2
```

**Comment by rck** [comment]
out of curiosity, can exec python in the container and provide the output of:
```
import locale
locale.getdefaultlocale()
```

**Comment by rck** [comment]
Okay, reproduced it, I guess it is `(None, None)`

**Comment by kvaps** [comment]
> Okay, reproduced it, I guess it is `(None, None)`

it is
```
root@linstor2-controller-0:/# python
Python 2.7.15+ (default, Nov 27 2018, 23:36:35) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> 
>>> locale.getdefaultlocale()
(None, None)
```

**Comment by kvaps** [comment]
agree fix is working on 1.0.1-1
